### ISSUE TITLE
error when parsing with HEAD

### ISSUE THREAD

**Issue by Sanqiang** [zhaohengyang/Generate-Parallel-Data-for-Sentence-Compression#1]
`Traceback (most recent call last):
  File "/Users/zhaosanqiang916/git/Generate-Parallel-Data-for-Sentence-Compression-master/python/test.py", line 74, in <module>
    reduce_sentence(sample)
  File "/Users/zhaosanqiang916/git/Generate-Parallel-Data-for-Sentence-Compression-master/python/test.py", line 24, in reduce_sentence
    sentence_reduction.transfer_tree()
  File "/Users/zhaosanqiang916/git/Generate-Parallel-Data-for-Sentence-Compression-master/python/parallel_data_gen.py", line 417, in transfer_tree
    self.transfered_tree.consistency()
  File "/Users/zhaosanqiang916/git/Generate-Parallel-Data-for-Sentence-Compression-master/python/parallel_data_gen.py", line 217, in consistency
    assert len(self.all_roots()) == 1
AssertionError`

Is there something wrong with this line of code?
I am using spacy 1.1.0 & latest one and python 2.7.

**Comment by sibredcat** [comment]
Hi Sanqiang!
Were you able to solve this issue? I got the same error.
